*creating a array named a*

In [1]:
import numpy as np

a= np.array([100,101,103])
a


array([100, 101, 103])

*creating a 2 dim array*

In [3]:
b = np.array([[1,2],[3,5]])
b


array([[1, 2],
       [3, 5]])

In [4]:
b = np.array([[1,2],[6,8]])
b.shape
b.ndim



2

*to show the value at that index*

In [ ]:
b[0,1]

In [ ]:
b[1,1
 ]

*creat a 3dim array*

In [ ]:
c = np.array([[[1,21,3,44],[0,-1,0,4],[1,6,8,4]],[[1,5,9,6],[5,6,7,2],[7,8,9,6]]])
c.ndim

*to get the value at that specific index*

In [ ]:
c[1,2,3]

In [ ]:
b[1,1]=20
b

In [ ]:
c.shape

In [ ]:
b.shape

*to see no of elements in the array*

In [ ]:
c.size

In [ ]:
b.size

In [ ]:
b.ndim

In [ ]:
np.array([0,4,5],dtype=str)

*to create a empty list*

In [ ]:
np.empty((2,3))

*create a list with all the elements as zeros*

In [ ]:
x = np.zeros((2,3,5))
x.size

In [ ]:
x = np.zeros((2,3), dtype=int)
x

In [ ]:
a


*printing the previously created multidimentional array*

In [ ]:
c


In [ ]:
b

*like  the array a , we create another array with all zeros*

In [ ]:
np.zeros_like(a, dtype=float)

*creating a list with range *

In [ ]:
q = list(range(9))
q

*generating array with a step(start,stop,step)*

In [ ]:
np.arange(1,9,0.4)

*generate evenly spaced elements(start,stop,no of numbers to be created)and if we add reshape it will convert it into no of array
*

In [9]:
np.linspace(3,9,6).reshape(2,3 )

array([[3. , 4.2, 5.4],
       [6.6, 7.8, 9. ]])

*retstep will show the deifference bet two consecutive number*

In [24]:
x = np.linspace (10,20,4, retstep= True)
x


(array([10.        , 13.33333333, 16.66666667, 20.        ]),
 3.3333333333333335)

*if endpoint is false it will not print the last element (and the difference bet two element will also change)*

In [32]:
y = np.linspace(5,25,3, endpoint=False)
y

array([ 5.        , 11.66666667, 18.33333333])

In [ ]:
*Initializing an array from a function*
 it is taking the index of the element (00,01,...) as ij and performing the action defines in the function.

In [35]:
def f(i,j):
    return 5+i+j

np.fromfunction(f,(2,3))

array([[5., 6., 7.],
       [6., 7., 8.]])

In [38]:
np.fromfunction(lambda i,j: 5+i+j,(2,3))

array([[5., 6., 7.],
       [6., 7., 8.]])

* here N is the size of the array and nth element  and in the function it is dividing the indexes (here i is 0toN-1) and divide by n here(4) where ever it is equal to 0 print 1 elso 0 * "The *1 is used to convert the boolean result to an integer (1 for True, 0 for False)."

In [41]:
N,n = 21,4
def f(i):
    return(i%n == 0)*1

comb = np.fromfunction(f,(N,),dtype = int)
comb

array([1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1])

In [ ]:
*created a ndarray and the shape gives the no of rows and cols*

In [54]:
a = np.array(((1,5,5),(7,89,8),(5,2,4),(4,5,6)))
a.shape

(4, 3)

In [53]:
a.ndim

2

In [57]:
a= np.array([[[1,2],[1,2]],[[1,2],[1,5]]])
a.shape

(2, 2, 2)

In [58]:
a.size

8

In [59]:
a.dtype

dtype('int32')

In [60]:
a.data

In [61]:
a.data

*it divided the array into two part and multiplied with 2*

In [79]:
x = np.linspace(1,10,3)
x

array([ 1. ,  5.5, 10. ])

In [71]:
x-1

array([0., 9.])

In [72]:
x-2

array([-1.,  8.])

In [73]:
np.sqrt(x-1)

array([0., 3.])

In [82]:
z = np.exp(-np.linspace(0,9,3))
np.sin(x-z)

array([ 0.        , -0.71336924, -0.54391756])

In [ ]:
*matrix multiplication in numpy*

In [87]:
a= np.array(((1,2),(1,2)))
b = np.array(((2,5),(2,3)))
c=a*b#elementwise multiplication
c

array([[ 2, 10],
       [ 2,  6]])

In [86]:
np.matmul(a,b)#proper multiplication

array([[ 6, 11],
       [ 6, 11]])

In [88]:
a.dot(b)

array([[ 6, 11],
       [ 6, 11]])

In [89]:
np.dot(a,b)

array([[ 6, 11],
       [ 6, 11]])

In [90]:
a*b

array([[ 2, 10],
       [ 2,  6]])

In [91]:
a@b

array([[ 6, 11],
       [ 6, 11]])

In [99]:

a = np.array(    [[1,2,3],[2,3,2]]  )
a.shape

(2, 3)

In [100]:
b = np.array([1,2])
b.shape

(2,)

*see the size and compute multiplication*

In [102]:
np.dot(b,a)

array([5, 8, 7])

*if the elements of the matrix is less than the given no then print true else false*

In [104]:
a<5

array([[ True,  True,  True],
       [ True,  True,  True]])

In [106]:
(a<2)|(a>5) # or operator

array([[ True, False, False],
       [False, False, False]])

*flatten: make a copy of the array and flattened it and ravel : made changes to the original copy itself*

In [114]:
a= np.array([[[1,2,2],[1,5,6],[4,5,6]],[[4,5,3],[4,5,5],[4,5,8]]])
b = a.flatten()#flatten reduced the dimention into one dim
a

array([[[1, 2, 2],
        [1, 5, 6],
        [4, 5, 6]],

       [[4, 5, 3],
        [4, 5, 5],
        [4, 5, 8]]])

In [119]:
b

array([1, 2, 2, 1, 5, 6, 4, 5, 6, 4, 5, 3, 4, 5, 5, 4, 5, 8])

In [116]:
b.shape

(18,)

In [117]:
a.shape

(2, 3, 3)

In [118]:
b[0]

1

In [120]:
c= a.ravel()
c

array([1, 2, 2, 1, 5, 6, 4, 5, 6, 4, 5, 3, 4, 5, 5, 4, 5, 8])

In [123]:
c[0]=5
c

array([5, 2, 2, 1, 5, 6, 4, 5, 6, 4, 5, 3, 4, 5, 5, 4, 5, 8])

In [124]:
a

array([[[5, 2, 2],
        [1, 5, 6],
        [4, 5, 6]],

       [[4, 5, 3],
        [4, 5, 5],
        [4, 5, 8]]])

In [126]:
c= a.flatten()
c

array([5, 2, 2, 1, 5, 6, 4, 5, 6, 4, 5, 3, 4, 5, 5, 4, 5, 8])

In [127]:
c[0]=8
c

array([8, 2, 2, 1, 5, 6, 4, 5, 6, 4, 5, 3, 4, 5, 5, 4, 5, 8])

In [128]:
a


array([[[5, 2, 2],
        [1, 5, 6],
        [4, 5, 6]],

       [[4, 5, 3],
        [4, 5, 5],
        [4, 5, 8]]])

*resize and rehshape*

In [129]:
a


array([[[5, 2, 2],
        [1, 5, 6],
        [4, 5, 6]],

       [[4, 5, 3],
        [4, 5, 5],
        [4, 5, 8]]])

In [137]:
d = np.linspace(1,10,12)
d

array([ 1.        ,  1.81818182,  2.63636364,  3.45454545,  4.27272727,
        5.09090909,  5.90909091,  6.72727273,  7.54545455,  8.36363636,
        9.18181818, 10.        ])

In [138]:
d. resize(2,3,2)
d

array([[[ 1.        ,  1.81818182],
        [ 2.63636364,  3.45454545],
        [ 4.27272727,  5.09090909]],

       [[ 5.90909091,  6.72727273],
        [ 7.54545455,  8.36363636],
        [ 9.18181818, 10.        ]]])

In [139]:
d.reshape(2,3,2)
d

array([[[ 1.        ,  1.81818182],
        [ 2.63636364,  3.45454545],
        [ 4.27272727,  5.09090909]],

       [[ 5.90909091,  6.72727273],
        [ 7.54545455,  8.36363636],
        [ 9.18181818, 10.        ]]])

In [140]:
d

array([[[ 1.        ,  1.81818182],
        [ 2.63636364,  3.45454545],
        [ 4.27272727,  5.09090909]],

       [[ 5.90909091,  6.72727273],
        [ 7.54545455,  8.36363636],
        [ 9.18181818, 10.        ]]])

In [165]:
v = np.array([1,2,3,3,5,6])
v

array([1, 2, 3, 3, 5, 6])

In [147]:
b=v.reshape(3,3)
b

ValueError: cannot reshape array of size 6 into shape (3,3)

In [150]:
b.size

6

In [151]:
b.shape


(3, 2)

In [153]:
v

array([1, 2, 3, 3, 5, 6, 7])

In [154]:
v.shape

(7,)

In [155]:
v.size

7

In [162]:
v.resize(3,2)
v

array([[1, 2],
       [3, 3],
       [5, 6]])

In [163]:
v.shape

(3, 2)

In [164]:
v.resize?

In [175]:
p=v.reshape(3,2)
p

array([[1, 2],
       [3, 9],
       [5, 6]])

In [167]:
v


array([1, 2, 3, 3, 5, 6])

In [169]:
v.reshape?

In [170]:
v.resize(3,2)
v

array([[1, 2],
       [3, 3],
       [5, 6]])

In [171]:
v


array([[1, 2],
       [3, 3],
       [5, 6]])

In [172]:
v.reshape(2,3)
v

array([[1, 2],
       [3, 3],
       [5, 6]])

In [173]:
v[1,1]= 9
v

array([[1, 2],
       [3, 9],
       [5, 6]])

In [174]:
v


array([[1, 2],
       [3, 9],
       [5, 6]])

In [186]:
a = np.array([[1,2],[5,3]])
a

array([[1, 2],
       [5, 3]])

In [181]:
a


array([1, 2, 3, 3])

In [187]:
b = a.transpose()
b

array([[1, 5],
       [2, 3]])

In [189]:
b.shape

(2, 2)

In [190]:
b.T

array([[1, 2],
       [5, 3]])

In [4]:
a= np.array([0,0,0,0])
b= np.array([1,1,1,1])
c=np.array([2,2,2,2])


In [192]:
b


array([1, 1, 1, 1])

In [193]:
a

array([0, 0, 0, 0])

In [195]:
np.dstack((a,c,b)
         )

array([[[0, 2, 1],
        [0, 2, 1],
        [0, 2, 1],
        [0, 2, 1]]])

In [10]:
np.hstack((c,b,c,a))# horizontally add arrays

array([2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2, 0, 0, 0, 0])

In [11]:
np.vstack((a,c,a,b))

array([[0, 0, 0, 0],
       [2, 2, 2, 2],
       [0, 0, 0, 0],
       [1, 1, 1, 1]])

In [9]:
np.hstack((a,b,a,c))

array([0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 2, 2, 2, 2])

In [13]:
np.dstack((a,b,c,a,b))

array([[[0, 1, 2, 0, 1],
        [0, 1, 2, 0, 1],
        [0, 1, 2, 0, 1],
        [0, 1, 2, 0, 1]]])

In [15]:
a = np.arange(6
            )
a

array([0, 1, 2, 3, 4, 5])

In [17]:
np.hsplit(a,2)#split divides the array into no of arrays

[array([0, 1, 2]), array([3, 4, 5])]

In [21]:
np.split(a,3)

[array([0, 1]), array([2, 3]), array([4, 5])]

In [24]:
a= np.linspace(10,16,6)
a

array([10. , 11.2, 12.4, 13.6, 14.8, 16. ])

In [29]:
a[0:6:3]# start:stop:step

array([10. , 13.6])

In [30]:
a[2::2]

array([12.4, 14.8])

In [34]:
a= np.linspace(1,12,12)
a

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [61]:
a= np.linspace(1,12,12).reshape(3,4)
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [38]:
a[2,3]

12.0

In [64]:
a[1:]

array([[ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [65]:
a[:,2] # print 3rd column

array([ 3.,  7., 11.])

In [69]:
s= np.linspace(1,12,12).reshape(4,3)
s

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

In [71]:
s[1:,1:3]

array([[ 5.,  6.],
       [ 8.,  9.],
       [11., 12.]])

In [75]:
s[3,1,...]

array(11.)

In [77]:
s[:,2]=1
s # set all element to equal number.

array([[ 1.,  2.,  1.],
       [ 4.,  5.,  1.],
       [ 7.,  8.,  1.],
       [10., 11.,  1.]])

In [78]:
h=np.linspace(1,10,10)
h

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [86]:
ih=[0,4,5]
h[ih]

array([1., 5., 6.])